version: "2"

services:
  contracts:
    image: "thunder_bridge_deployer"
    build: ../contracts
    command: bash
    volumes:
      - /contracts
      - ../contracts/contracts:/contracts/contracts
      - ../contracts/migrations:/contracts/migrations

  truffle:
    image: "trufflesuite/ganache-cli:latest"
    ports:
     - "7545:8545"
    command: "-m 'wisdom zero output drift choice bright east stuff craft inform invest patient' --callGasLimit 10000000000000 -l 10000000000000 -g 10000000000000000 -e 10000000000000 -i 5777"

  pala:
    image: "pala-for-truffle-test"
    build: e2e/thunder
    restart: always
    ports:
     - "7545:8545"

  truffle-test:
    network_mode: host
    build: .
    stdin_open: true
    env_file:
      - ./envs/truffle.env
    tty: true
    volumes_from:
      - contracts:rw
    volumes:
      - ./truffle-test:/app/truffle-test
      - ./data:/app/data
    command: npm run truffle-test
    depends_on:
      - truffle
      - contracts

  redis:
    image: "redis:4"
    ports:
     - "6379:6379"
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 15672:15672
      - 5672:5672
