version: '2'
services:
  validator:
    build: ..
    image: validator
    network_mode: host
    environment:
      - SENTRY_ENVIRONMENT=local
      - NODE_ENV=test
      - BRIDGE_MODE=ERC_TO_ERC
      - QUEUE_URL=amqp://127.0.0.1:5672
      - REDIS_URL=redis://127.0.0.1:6379
      - HOME_RPC_URL=http://127.0.0.1:8541
      - FOREIGN_RPC_URL=http://127.0.0.1:8542
      - HOME_START_BLOCK=0
      - FOREIGN_START_BLOCK=0
      - REDIS_LOCK_TTL=1000
      - HOME_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
      - HOME_GAS_PRICE_FALLBACK=1000000000
      - HOME_GAS_PRICE_UPDATE_INTERVAL=600000
      - FOREIGN_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
      - FOREIGN_GAS_PRICE_FALLBACK=10000000000
      - FOREIGN_GAS_PRICE_UPDATE_INTERVAL=600000
      - HOME_POLLING_INTERVAL=2000
      - FOREIGN_POLLING_INTERVAL=2000
      - ALLOW_HTTP=yes
      - HOME_BLOCK_CONFIRMATION=13
      - FOREIGN_BLOCK_CONFIRMATION=13
      - MAX_WAIT_RECEIPT_BLOCK=2
      - GET_RECEIPT_TIMEOUT=5000
      - LOAD_DEPLOYED_CONTRACT=yes
      - EXTRA_GAS_PERCENTAGE=0
      - HOME_VALIDATOR_REQUIRED_BALANCE=0.1
      - FOREIGN_VALIDATOR_REQUIRED_BALANCE=0.1
    volumes:
      - ../src:/app/src
      - ../scripts:/app/scripts
    env_file:
      - ./validator.env
  watcher-signature-request:
    extends: validator
    restart: always
    command: npm run watcher:signature-request
  watcher-collected-signatures:
    extends: validator
    restart: always
    command: npm run watcher:collected-signatures
  watcher-affirmation-request:
    extends: validator
    restart: always
    command: npm run watcher:affirmation-request
  sender-home:
    extends: validator
    restart: always
    command: npm run sender:home
  sender-foreign:
    extends: validator
    restart: always
    command: npm run sender:foreign
  receiptor-home:
    extends: validator
    restart: always
    command: npm run receiptor:home
  receiptor-foreign:
    extends: validator
    restart: always
    command: npm run receiptor:foreign
