version: '2'
services:
  parity1:
    build: parity
    ports:
      - "8541:8545"
  parity2:
    build: parity
    ports:
      - "8542:8545"
  redis:
    image: "redis:4"
  rabbit:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
  bridge:
    build: ..
    environment:
      - NODE_ENV=test
      - BRIDGE_MODE=ERC_TO_ERC
      - QUEUE_URL=amqp://rabbit
      - REDIS_URL=redis://redis
      - HOME_RPC_URL=http://parity1:8545
      - FOREIGN_RPC_URL=http://parity2:8545
      - HOME_START_BLOCK=0
      - FOREIGN_START_BLOCK=0
      - HOME_BRIDGE_ADDRESS=0x32198D570fffC7033641F8A9094FFDCaAEF42624
      - FOREIGN_BRIDGE_ADDRESS=0x5118AC62AE912Dd5B51EEfF7338c4fcb0248Ba8c
      - ERC20_TOKEN_ADDRESS=0xdbeE25CbE97e4A5CC6c499875774dc7067E9426B
      - BRIDGEABLE_TOKEN_ADDRESS=0xE0CCE6C39cA0cB5699e8a607c4B9eC6248C85F9f
      - VALIDATOR_ADDRESS=0xaaB52d66283F7A1D5978bcFcB55721ACB467384b
      - VALIDATOR_ADDRESS_PRIVATE_KEY=8e829f695aed89a154550f30262f1529582cc49dc30eff74a6b491359e0230f9
      - REDIS_LOCK_TTL=1000
      - HOME_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
      - HOME_GAS_PRICE_FALLBACK=1000000000
      - HOME_GAS_PRICE_UPDATE_INTERVAL=600000
      - FOREIGN_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
      - FOREIGN_GAS_PRICE_FALLBACK=10000000000
      - FOREIGN_GAS_PRICE_UPDATE_INTERVAL=600000
      - HOME_POLLING_INTERVAL=2000
      - FOREIGN_POLLING_INTERVAL=2000
      - ALLOW_HTTP=yes
    volumes:
      - ../src:/app/src
  watcher-signature-request:
    extends: bridge
    command: npm run watcher:signature-request
  watcher-collected-signatures:
    extends: bridge
    command: npm run watcher:collected-signatures
  watcher-affirmation-request:
    extends: bridge
    command: npm run watcher:affirmation-request
  sender-home:
    extends: bridge
    command: npm run sender:home
  test:
    extends: bridge
    command: bash
    stdin_open: true
    tty: true
  sender-foreign:
    extends: bridge
    command: npm run sender:foreign
  e2e:
    build:
        context: ../../
        dockerfile: ./validator/e2e/Dockerfile
    command:
      - "true"
  deploy-contract:
    extends: e2e
    command: npm run deploy
    volumes:
      - ./test:/stuff/test
    depends_on:
      - parity1
      - parity2
      - rabbit
      - redis
