version: '2'
services:
  home-chain:
    build: parity
    ports:
      - "8541:8545"
  foreign-chain:
    build: parity
    ports:
      - "8542:8545"
  redis:
    image: "redis:4"
    ports:
     - "6379:6379"
  rabbit:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
  validator:
    build: ..
    image: validator
    network_mode: host
    environment:
      - NODE_ENV=test
      - BRIDGE_MODE=ERC_TO_ERC
      - QUEUE_URL=amqp://127.0.0.1:5672
      - REDIS_URL=redis://127.0.0.1:6379
      - HOME_RPC_URL=http://127.0.0.1:8541
      - FOREIGN_RPC_URL=http://127.0.0.1:8542
      - HOME_START_BLOCK=0
      - FOREIGN_START_BLOCK=0
      - REDIS_LOCK_TTL=1000
      - HOME_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
      - HOME_GAS_PRICE_FALLBACK=1000000000
      - HOME_GAS_PRICE_UPDATE_INTERVAL=600000
      - FOREIGN_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
      - FOREIGN_GAS_PRICE_FALLBACK=10000000000
      - FOREIGN_GAS_PRICE_UPDATE_INTERVAL=600000
      - HOME_POLLING_INTERVAL=2000
      - FOREIGN_POLLING_INTERVAL=2000
      - ALLOW_HTTP=yes
      - BLOCK_CONFIRMATION=13
      - MAX_WAIT_RECEIPT_BLOCK=2
      - GET_RECEIPT_TIMEOUT=5000
      - LOAD_DEPLOYED_CONTRACT=yes
    volumes:
      - ../src:/app/src
      - ../scripts:/app/scripts
  watcher-signature-request:
    extends: validator
    command: npm run watcher:signature-request
  watcher-collected-signatures:
    extends: validator
    command: npm run watcher:collected-signatures
  watcher-affirmation-request:
    extends: validator
    command: npm run watcher:affirmation-request
  sender-home:
    extends: validator
    command: npm run sender:home
    environment:
      - VALIDATOR_ADDRESS=0x0b663c33A72819d2371Ad7939A4C29dc31C0881b
      - VALIDATOR_ADDRESS_PRIVATE_KEY=4bf3b1bb36eb3f53d1ae5e6309510e17fe41df9a26a236de3385872211e0eab4
  sender-foreign:
    extends: validator
    command: npm run sender:foreign
    environment:
      - VALIDATOR_ADDRESS=0x0b663c33A72819d2371Ad7939A4C29dc31C0881b
      - VALIDATOR_ADDRESS_PRIVATE_KEY=4bf3b1bb36eb3f53d1ae5e6309510e17fe41df9a26a236de3385872211e0eab4
  receiptor-home:
    extends: validator
    command: npm run receiptor:home
  receiptor-foreign:
    extends: validator
    command: npm run receiptor:foreign
  e2e:
    build: .
    image: e2e
    stdin_open: true
    tty: true