version: '2'
services:
  home-chain:
    build: thunder
    ports:
      - "8540:8546"
      - "8541:8545"
  foreign-chain:
    build: thunder
    ports:
      - "8542:8545"
  redis:
    image: "redis:4"
    ports:
     - "6379:6379"
  rabbit:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"